CREATE TABLE "news_articles" (
    "id" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "category" TEXT NOT NULL DEFAULT 'official',
    "coverImage" TEXT,
    "documentUrl" TEXT,
    "sourceName" TEXT NOT NULL,
    "published" BOOLEAN NOT NULL DEFAULT false,
    "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "titleFr" TEXT NOT NULL,
    "titleEn" TEXT NOT NULL,
    "excerptFr" TEXT NOT NULL,
    "excerptEn" TEXT NOT NULL,
    "categoryLabelFr" TEXT,
    "categoryLabelEn" TEXT,
    "readTimeFr" TEXT,
    "readTimeEn" TEXT,
    "heroEyebrowFr" TEXT,
    "heroEyebrowEn" TEXT,
    "sourceLabelFr" TEXT,
    "sourceLabelEn" TEXT,
    "pdfLabelFr" TEXT,
    "pdfLabelEn" TEXT,
    "keyPointsTitleFr" TEXT,
    "keyPointsTitleEn" TEXT,
    "keyPointsFr" TEXT[],
    "keyPointsEn" TEXT[],
    "paragraphsFr" TEXT[],
    "paragraphsEn" TEXT[],
    "ctaTitleFr" TEXT,
    "ctaTitleEn" TEXT,
    "ctaTextFr" TEXT,
    "ctaTextEn" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "news_articles_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "news_articles_slug_key" ON "news_articles"("slug");

INSERT INTO "news_articles" (
    "id",
    "slug",
    "category",
    "coverImage",
    "documentUrl",
    "sourceName",
    "published",
    "publishedAt",
    "titleFr",
    "titleEn",
    "excerptFr",
    "excerptEn",
    "categoryLabelFr",
    "categoryLabelEn",
    "readTimeFr",
    "readTimeEn",
    "heroEyebrowFr",
    "heroEyebrowEn",
    "sourceLabelFr",
    "sourceLabelEn",
    "pdfLabelFr",
    "pdfLabelEn",
    "keyPointsTitleFr",
    "keyPointsTitleEn",
    "keyPointsFr",
    "keyPointsEn",
    "paragraphsFr",
    "paragraphsEn",
    "ctaTitleFr",
    "ctaTitleEn",
    "ctaTextFr",
    "ctaTextEn"
) VALUES (
    'news_arrete_18280_2026',
    'arrete-18280-2026-campagne-vanille-verte-sofia-diana-anosy',
    'official',
    '/photos-produit-vanille/galerie-photos-qui-sommes-nous/vanilles-traitees.jpg',
    '/documents/arrete-18280-2026-campagne-vanille-verte-sofia-diana-anosy.pdf',
    'Arrete interministeriel n18280/2026',
    true,
    '2026-05-29T00:00:00.000Z',
    'Arrete n18280/2026 - Ouverture de la campagne vanille verte 2026-2027',
    'Order n18280/2026 - Opening of the 2026-2027 green vanilla campaign',
    'Les regions SOFIA, DIANA et ANOSY sont concernees par l ouverture de la campagne de commercialisation de la vanille verte 2026-2027 a Madagascar.',
    'The SOFIA, DIANA and ANOSY regions are covered by the opening of Madagascar s 2026-2027 green vanilla marketing campaign.',
    'Actualite officielle',
    'Official update',
    '3 min',
    '3 min read',
    'Filiere vanille Madagascar',
    'Madagascar vanilla industry',
    'Source officielle',
    'Official source',
    'Telecharger l arrete PDF',
    'Download the official PDF',
    'Points a retenir',
    'Key takeaways',
    ARRAY[
        'La commercialisation de la vanille verte est encadree par arrete interministeriel.',
        'Les regions SOFIA, DIANA et ANOSY sont mentionnees pour la campagne 2026-2027.',
        'Ces mesures visent a proteger la maturite, la qualite et la tracabilite de la vanille malgache.'
    ],
    ARRAY[
        'Green vanilla marketing in Madagascar is regulated by interministerial orders.',
        'The SOFIA, DIANA and ANOSY regions are mentioned for the 2026-2027 campaign.',
        'These measures help protect maturity, quality and traceability across the Malagasy vanilla sector.'
    ],
    ARRAY[
        'La campagne de commercialisation de la vanille verte a Madagascar fait l objet d un encadrement officiel afin de garantir une recolte arrivee a maturite et de preserver la reputation internationale de la vanille malgache.',
        'L arrete n18280/2026 relatif a l ouverture de la campagne vanille verte 2026-2027 concerne notamment les regions SOFIA, DIANA et ANOSY. Ce type de decision permet aux producteurs, collecteurs, exportateurs et partenaires internationaux de suivre un calendrier commun.',
        'Pour M.S.V-Nosy Be Madagascar, le suivi de ces informations officielles est essentiel: il participe a la transparence de la filiere, a la selection de produits de qualite et a l information des clients professionnels comme particuliers.'
    ],
    ARRAY[
        'Madagascar s green vanilla marketing campaigns are officially regulated to ensure that beans are harvested at the right maturity stage and to preserve the international reputation of Malagasy vanilla.',
        'Order n18280/2026 concerning the opening of the 2026-2027 green vanilla campaign covers, in particular, the SOFIA, DIANA and ANOSY regions. This type of official decision gives producers, collectors, exporters and international partners a shared campaign calendar.',
        'For M.S.V-Nosy Be Madagascar, monitoring official information is part of a transparent and professional approach. It supports quality selection and helps inform both retail customers and international partners.'
    ],
    'Pourquoi suivre ces actualites ?',
    'Why follow these updates?',
    'Les arretes, informations ministerielles et tendances du marche donnent une lecture plus claire des conditions de recolte, des volumes disponibles et de la qualite attendue sur chaque campagne.',
    'Official orders, ministry updates and market trends provide clearer visibility on harvest conditions, available volumes and expected quality for each campaign.'
);
